/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.navi.frontend.views;

import java.awt.*;

/**
 *
 * @author dog
 */
public class Parser extends javax.swing.JPanel {

    /**
     * Creates new form Parser
     */
    public Parser() {
        initComponents();
        initStyles();
        
    }
    
    private void initStyles(){
        textPaneParser.setForeground(Color.BLACK);
        textPaneError.setForeground(Color.BLACK);
        //Obscure Theme
        textPaneParser.setForeground(Color.WHITE);
        textPaneError.setForeground(Color.WHITE);

        textPaneError.setEditable(false);
        
        errorLabel.putClientProperty("FlatLaf.style","font: bold $h3.regular.font");
        errorLabel.setForeground(Color.WHITE);
        parserButton.setForeground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPaneParser = new javax.swing.JScrollPane();
        textPaneParser = new javax.swing.JTextPane();
        jScrollPaneError = new javax.swing.JScrollPane();
        textPaneError = new javax.swing.JTextPane();
        errorLabel = new javax.swing.JLabel();
        parserButton = new javax.swing.JButton();

        background.setBackground(new Color(0, 153, 153));

        jScrollPaneParser.setViewportView(textPaneParser);

        jScrollPaneError.setViewportView(textPaneError);

        errorLabel.setText("ERROR");

        parserButton.setBackground(new Color(0, 204, 204));
        parserButton.setFont(new Font("Liberation Sans", 0, 14)); // NOI18N
        parserButton.setText("Analizar");
        parserButton.setBorder(null);
        parserButton.setBorderPainted(false);
        parserButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneError)
                    .addComponent(jScrollPaneParser)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addGap(471, 471, 471)))
                .addGap(18, 18, 18)
                .addComponent(parserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(parserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPaneParser, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneError, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JScrollPane jScrollPaneError;
    private javax.swing.JScrollPane jScrollPaneParser;
    private javax.swing.JButton parserButton;
    private javax.swing.JTextPane textPaneError;
    private javax.swing.JTextPane textPaneParser;
    // End of variables declaration//GEN-END:variables
}
