package frontend;

import backend.Analyzer;
import backend.ReaderText;
import backend.Token;
import backend.TokenType;

import javax.swing.*;
import java.awt.*;

public class UI extends javax.swing.JFrame {
    Analyzer analyzer;
    SimpleList simpleList;
    CreateHTML png;
    PNGFrame pngFrame;
    LineNumber lineNumber, lineNumber2, lineNumber3;
    Reports reports;
    String comboBoxID,comboBoxArithmetic,comboBoxAssign,comboBoxComment,
            comboBoxKeyWord, comboBoxComparison, comboBoxConstant, comboBoxOthers;

    public UI() {

        initComponents();
        jComboBoxID.setEditable(true);
        jComboBoxArithmetic.setEditable(true);
        jComboBoxAssign.setEditable(true);
        jComboBoxComment.setEditable(true);
        jComboBoxKeyWords.setEditable(true);
        jComboBoxComparison.setEditable(true);
        jComboBoxConstant.setEditable(true);
        jComboBoxOthers.setEditable(true);

        jPanelGraphviz.setOpaque(false);

        jPanelReportTable.removeAll();
        jPanelReportTable.setLayout(new BorderLayout(0,0));
        jPanelReportTable.setBackground(Color.black);

        lineNumber = new LineNumber(jTextPaneAnalyze);
        lineNumber2 = new LineNumber(jTextPaneError);
        lineNumber3 = new LineNumber(jTextPanePaint);

        jScrollPane1.setRowHeaderView(lineNumber);
        jScrollPane2.setRowHeaderView(lineNumber2);
        jScrollPane3.setRowHeaderView(lineNumber3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelFile = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneAnalyze = new javax.swing.JTextPane();
        jPanelAnalyze = new javax.swing.JPanel();
        jLabelAnalyze = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneError = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        //jPanelPaint = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPanePaint = new javax.swing.JTextPane();
        jPanelGraph = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jComboBoxID = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButtonID = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jComboBoxArithmetic = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButtonArithmetic = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jComboBoxComparison = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButtonComparison = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jComboBoxAssign = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButtonAssign = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jComboBoxKeyWords = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jButtonKeyWords = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jComboBoxConstant = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButtonConstant = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jComboBoxComment = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButtonComment = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jComboBoxOthers = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jButtonOthers = new javax.swing.JButton();
        jPanelGraphviz = new javax.swing.JEditorPane();
        jPanelReport = new javax.swing.JPanel();
        jPanelReportTable = new javax.swing.JPanel();
        jButtonReportAll = new javax.swing.JButton();
        jButtonReportID = new javax.swing.JButton();
        jButtonReportArithmetic = new javax.swing.JButton();
        jButtonReportCompare = new javax.swing.JButton();
        jButtonReportAssign = new javax.swing.JButton();
        jButtonReportKeyWord = new javax.swing.JButton();
        jButtonReportConstant = new javax.swing.JButton();
        jButtonReportComment = new javax.swing.JButton();
        jButtonReportOthers = new javax.swing.JButton();
        jButtonReportErr = new javax.swing.JButton();
        jPanelHelp = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaAbout1 = new javax.swing.JTextArea();
        jPanelAbout = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaAbout = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCentral.setBackground(new java.awt.Color(51, 255, 255));
        jPanelCentral.setPreferredSize(new java.awt.Dimension(880, 670));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanelFile.setBackground(new java.awt.Color(0, 105, 105));

        jScrollPane1.setViewportView(jTextPaneAnalyze);

        jPanelAnalyze.setBackground(new java.awt.Color(51, 255, 204));

        jLabelAnalyze.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabelAnalyze.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnalyze.setText("Analizar");
        jLabelAnalyze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAnalyze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAnalyzeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnalyzeLayout = new javax.swing.GroupLayout(jPanelAnalyze);
        jPanelAnalyze.setLayout(jPanelAnalyzeLayout);
        jPanelAnalyzeLayout.setHorizontalGroup(
                jPanelAnalyzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelAnalyze, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanelAnalyzeLayout.setVerticalGroup(
                jPanelAnalyzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelAnalyze, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jTextPaneError);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("ERROR");

        javax.swing.GroupLayout jPanelFileLayout = new javax.swing.GroupLayout(jPanelFile);
        jPanelFile.setLayout(jPanelFileLayout);
        jPanelFileLayout.setHorizontalGroup(
                jPanelFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFileLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanelFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelFileLayout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(819, Short.MAX_VALUE))
                                        .addGroup(jPanelFileLayout.createSequentialGroup()
                                                .addGroup(jPanelFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane2)
                                                        .addComponent(jScrollPane1))
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanelAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32))))
        );
        jPanelFileLayout.setVerticalGroup(
                jPanelFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFileLayout.createSequentialGroup()
                                .addGroup(jPanelFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelFileLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jPanelAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelFileLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Archivo", jPanelFile);

        //jPanelPaint.setBackground(new java.awt.Color(0, 105, 105));

        jScrollPane3.setViewportView(jTextPanePaint);

/*        javax.swing.GroupLayout jPanelPaintLayout = new javax.swing.GroupLayout(jPanelPaint);
        jPanelPaint.setLayout(jPanelPaintLayout);
        jPanelPaintLayout.setHorizontalGroup(
                jPanelPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaintLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                                .addGap(43, 43, 43))
        );
        jPanelPaintLayout.setVerticalGroup(
                jPanelPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPaintLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Pintar", jPanelPaint);*/

        jPanelGraph.setBackground(new java.awt.Color(0, 51, 102));

        jPanel17.setBackground(new java.awt.Color(0, 51, 102));
        jPanel17.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Identificadores");

        jButtonID.setBackground(new java.awt.Color(0, 0, 0));
        jButtonID.setForeground(new java.awt.Color(255, 255, 255));
        jButtonID.setText("Crear");
        jButtonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxID, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonID))
        );

        jPanel21.setBackground(new java.awt.Color(0, 51, 102));
        jPanel21.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxArithmetic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxArithmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxArithmeticActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Aritméticos");

        jButtonArithmetic.setBackground(new java.awt.Color(0, 0, 0));
        jButtonArithmetic.setForeground(new java.awt.Color(255, 255, 255));
        jButtonArithmetic.setText("Crear");
        jButtonArithmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArithmeticActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxArithmetic, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonArithmetic, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxArithmetic, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonArithmetic))
        );

        jPanel24.setBackground(new java.awt.Color(0, 51, 102));
        jPanel24.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxComparison.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxComparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComparisonActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Comparación");

        jButtonComparison.setBackground(new java.awt.Color(0, 0, 0));
        jButtonComparison.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComparison.setText("Crear");
        jButtonComparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComparisonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxComparison, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonComparison, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxComparison, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonComparison))
        );

        jPanel25.setBackground(new java.awt.Color(0, 51, 102));
        jPanel25.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxAssign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAssignActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Asignación");

        jButtonAssign.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAssign.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAssign.setText("Crear");
        jButtonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
                jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
                jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxAssign, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAssign))
        );

        jPanel26.setBackground(new java.awt.Color(0, 51, 102));
        jPanel26.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxKeyWords.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxKeyWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKeyWordsActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Palabras clave");

        jButtonKeyWords.setBackground(new java.awt.Color(0, 0, 0));
        jButtonKeyWords.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKeyWords.setText("Crear");
        jButtonKeyWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeyWordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxKeyWords, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonKeyWords))
        );

        jPanel27.setBackground(new java.awt.Color(0, 51, 102));
        jPanel27.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxConstant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxConstant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConstantActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Constantes");

        jButtonConstant.setBackground(new java.awt.Color(0, 0, 0));
        jButtonConstant.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConstant.setText("Crear");
        jButtonConstant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConstantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
                jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxConstant, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConstant, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
                jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxConstant, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonConstant))
        );

        jPanel28.setBackground(new java.awt.Color(0, 51, 102));
        jPanel28.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxComment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCommentActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Comentarios");

        jButtonComment.setBackground(new java.awt.Color(0, 0, 0));
        jButtonComment.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComment.setText("Crear");
        jButtonComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
                jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxComment, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonComment, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
                jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxComment, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonComment))
        );

        jPanel30.setBackground(new java.awt.Color(0, 51, 102));
        jPanel30.setForeground(new java.awt.Color(0, 51, 153));

        jComboBoxOthers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOthersActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Otros");

        jButtonOthers.setBackground(new java.awt.Color(0, 0, 0));
        jButtonOthers.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOthers.setText("Crear");
        jButtonOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOthersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
                jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxOthers, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonOthers, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
                jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxOthers, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOthers))
        );

        javax.swing.GroupLayout jPanelGraphLayout = new javax.swing.GroupLayout(jPanelGraph);
        jPanelGraph.setLayout(jPanelGraphLayout);
        jPanelGraphLayout.setHorizontalGroup(
                jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGraphLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addComponent(jPanelGraphviz, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
        );
        jPanelGraphLayout.setVerticalGroup(
                jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGraphLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelGraphviz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelGraphLayout.createSequentialGroup()
                                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generar Grafico", jPanelGraph);

        jPanelReport.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanelReportTable);
        jPanelReportTable.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 420, Short.MAX_VALUE)
        );

        jButtonReportAll.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportAll.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportAll.setText("Todos");
        jButtonReportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportAllActionPerformed(evt);
            }
        });

        jButtonReportID.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportID.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportID.setText("Identificadores");
        jButtonReportID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportIDActionPerformed(evt);
            }
        });

        jButtonReportArithmetic.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportArithmetic.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportArithmetic.setText("Aritméticos");
        jButtonReportArithmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportArithmeticActionPerformed(evt);
            }
        });

        jButtonReportCompare.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportCompare.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportCompare.setText("Comparación");
        jButtonReportCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportCompareActionPerformed(evt);
            }
        });

        jButtonReportAssign.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportAssign.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportAssign.setText("Asignación");
        jButtonReportAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportAssignActionPerformed(evt);
            }
        });

        jButtonReportKeyWord.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportKeyWord.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportKeyWord.setText("Palabra clave");
        jButtonReportKeyWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportKeyWordActionPerformed(evt);
            }
        });

        jButtonReportConstant.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportConstant.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportConstant.setText("Constantes");
        jButtonReportConstant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportConstantActionPerformed(evt);
            }
        });

        jButtonReportComment.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportComment.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportComment.setText("Comentarios");
        jButtonReportComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportCommentActionPerformed(evt);
            }
        });

        jButtonReportOthers.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportOthers.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportOthers.setText("Otros");
        jButtonReportOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportOthersActionPerformed(evt);
            }
        });

        jButtonReportErr.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportErr.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportErr.setText("Errores");
        jButtonReportErr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportErrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReportLayout = new javax.swing.GroupLayout(jPanelReport);
        jPanelReport.setLayout(jPanelReportLayout);
        jPanelReportLayout.setHorizontalGroup(
                jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelReportTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelReportLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonReportKeyWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonReportID, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(jButtonReportConstant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(77, 77, 77)
                                .addGroup(jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonReportArithmetic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportComment, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addGroup(jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonReportOthers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportCompare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67)
                                .addGroup(jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonReportAssign, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(jButtonReportErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
        );
        jPanelReportLayout.setVerticalGroup(
                jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReportLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonReportAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportArithmetic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportCompare)
                                        .addComponent(jButtonReportAssign)
                                        .addComponent(jButtonReportID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonReportOthers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportErr)
                                        .addComponent(jButtonReportComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportConstant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportKeyWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanelReportTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Reporte", jPanelReport);

        jPanelHelp.setBackground(new java.awt.Color(0, 216, 118));

        jTextAreaAbout1.setColumns(20);
        jTextAreaAbout1.setRows(5);
        jScrollPane5.setViewportView(jTextAreaAbout1);

        javax.swing.GroupLayout jPanelHelpLayout = new javax.swing.GroupLayout(jPanelHelp);
        jPanelHelp.setLayout(jPanelHelpLayout);
        jPanelHelpLayout.setHorizontalGroup(
                jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHelpLayout.createSequentialGroup()
                                .addContainerGap(61, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
        );
        jPanelHelpLayout.setVerticalGroup(
                jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHelpLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ayuda", jPanelHelp);

        jPanelAbout.setBackground(new java.awt.Color(0, 216, 118));

        jTextAreaAbout.setColumns(20);
        jTextAreaAbout.setRows(5);
        jScrollPane4.setViewportView(jTextAreaAbout);

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
                jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAboutLayout.createSequentialGroup()
                                .addContainerGap(61, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
        );
        jPanelAboutLayout.setVerticalGroup(
                jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAboutLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acerca de", jPanelAbout);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
                jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );
        jPanelCentralLayout.setVerticalGroup(
                jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Cargar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }
    private boolean isValidLexeme(TokenType type, String text){
        for (Token token : analyzer.filterArrayList(type)) {
            if(token.getLexem().equals(text)){
                return true;
            }
        }
        return false;
    }
    private void jComboBoxIDActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            comboBoxID = jComboBoxID.getSelectedItem().toString();
            if(isValidLexeme(TokenType.IDENTIFIER, comboBoxID)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxID);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}

    }

    private void jComboBoxOthersActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            comboBoxOthers = jComboBoxOthers.getSelectedItem().toString();
            if(isValidLexeme(TokenType.OTHERS, comboBoxOthers)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxOthers);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}
    }

    private void jButtonIDActionPerformed(java.awt.event.ActionEvent evt) {
        png = new CreateHTML();
        png.showHTML(jPanelGraphviz);
        pngFrame = new PNGFrame();
        pngFrame.init(jPanelGraphviz);
        SwingUtilities.updateComponentTreeUI(jPanelGraphviz);
    }

    private void jButtonArithmeticActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonComparisonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonAssignActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonKeyWordsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonConstantActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonCommentActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonOthersActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxArithmeticActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            comboBoxArithmetic = jComboBoxArithmetic.getSelectedItem().toString();
            if(isValidLexeme(TokenType.ARITHMETIC,comboBoxArithmetic)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxArithmetic);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}
    }

    private void jComboBoxComparisonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            comboBoxComparison = jComboBoxComparison.getSelectedItem().toString();
            if(isValidLexeme(TokenType.COMPARASION,comboBoxComparison)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxComparison);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}
    }

    private void jComboBoxAssignActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            comboBoxAssign = jComboBoxAssign.getSelectedItem().toString();
            if(isValidLexeme(TokenType.ASSIGNMENT,comboBoxAssign)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxAssign);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}
    }

    private void jComboBoxKeyWordsActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            comboBoxKeyWord = jComboBoxKeyWords.getSelectedItem().toString();
            if(isValidLexeme(TokenType.KEYWORD,comboBoxKeyWord)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxKeyWord);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}
    }

    private void jComboBoxConstantActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            comboBoxConstant = jComboBoxConstant.getSelectedItem().toString();
            if(isValidLexeme(TokenType.CONSTANT,comboBoxConstant)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxConstant);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}
    }

    private void jComboBoxCommentActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            comboBoxComment = jComboBoxComment.getSelectedItem().toString();
            if(isValidLexeme(TokenType.COMMENT,comboBoxComment)){
                simpleList = new SimpleList();
                simpleList.setNodes(comboBoxComment);
                simpleList.drawGraphviz();
            }
        } catch (Exception e){}
    }

    private void jLabelAnalyzeMouseClicked(java.awt.event.MouseEvent evt) {
        analyzer = new Analyzer(jTextPaneAnalyze.getText());
        analyzer.analyze();
        jTextPaneError.setText(analyzer.filterArrayList(TokenType.ERROR).toString());
        PaintWords paintWords = new PaintWords();
        paintWords.setStyle(jTextPaneAnalyze.getText());
        paintWords.paintTokens(analyzer);

        fillComboBox();

        //PRUEBA REPORTS
        reports = new Reports(analyzer.getTokens());
        jPanelReportTable.removeAll();
        reports.table(jPanelReportTable);

        jTextPaneAnalyze.setDocument(paintWords.textPane.getDocument());
        jTextPanePaint.setDocument(paintWords.textPane.getDocument());
    }

    private void fillComboBox(){
        jComboBoxID.removeAllItems();
        jComboBoxArithmetic.removeAllItems();
        jComboBoxAssign.removeAllItems();
        jComboBoxComment.removeAllItems();
        jComboBoxKeyWords.removeAllItems();
        jComboBoxComparison.removeAllItems();
        jComboBoxConstant.removeAllItems();
        jComboBoxOthers.removeAllItems();

        for (Token token : analyzer.filterArrayList(TokenType.IDENTIFIER)) {
            jComboBoxID.addItem(token.getLexem());
        }
        for (Token token : analyzer.filterArrayList(TokenType.ARITHMETIC)) {
            jComboBoxArithmetic.addItem(token.getLexem());
        }
        for (Token token : analyzer.filterArrayList(TokenType.COMPARASION)) {
            jComboBoxComparison.addItem(token.getLexem());
        }
        for (Token token : analyzer.filterArrayList(TokenType.ASSIGNMENT)) {
            jComboBoxAssign.addItem(token.getLexem());
        }
        for (Token token : analyzer.filterArrayList(TokenType.KEYWORD)) {
            jComboBoxKeyWords.addItem(token.getLexem());
        }
        for (Token token : analyzer.filterArrayList(TokenType.CONSTANT)) {
            jComboBoxConstant.addItem(token.getLexem());
        }
        for (Token token : analyzer.filterArrayList(TokenType.COMMENT)) {
            jComboBoxComment.addItem(token.getLexem());
        }
        for (Token token : analyzer.filterArrayList(TokenType.OTHERS)) {
            jComboBoxOthers.addItem(token.getLexem());
        }
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        jTextPaneAnalyze.setText(ReaderText.Read());
    }

    private void jButtonReportCommentActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.COMMENT));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportAllActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.getTokens());
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportIDActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.IDENTIFIER));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportArithmeticActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.ARITHMETIC));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportCompareActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.COMPARASION));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportAssignActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.ASSIGNMENT));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportKeyWordActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.KEYWORD));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportConstantActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.CONSTANT));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportOthersActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.OTHERS));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }

    private void jButtonReportErrActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            reports = new Reports(analyzer.filterArrayList(TokenType.ERROR));
            jPanelReportTable.removeAll();
            reports.table(jPanelReportTable);
            SwingUtilities.updateComponentTreeUI(jPanelReportTable);
        } catch (Exception e){

        }
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonArithmetic;
    private javax.swing.JButton jButtonAssign;
    private javax.swing.JButton jButtonComment;
    private javax.swing.JButton jButtonComparison;
    private javax.swing.JButton jButtonConstant;
    private javax.swing.JButton jButtonID;
    private javax.swing.JButton jButtonKeyWords;
    private javax.swing.JButton jButtonOthers;
    private javax.swing.JButton jButtonReportAll;
    private javax.swing.JButton jButtonReportArithmetic;
    private javax.swing.JButton jButtonReportAssign;
    private javax.swing.JButton jButtonReportComment;
    private javax.swing.JButton jButtonReportCompare;
    private javax.swing.JButton jButtonReportConstant;
    private javax.swing.JButton jButtonReportErr;
    private javax.swing.JButton jButtonReportID;
    private javax.swing.JButton jButtonReportKeyWord;
    private javax.swing.JButton jButtonReportOthers;
    private javax.swing.JComboBox<String> jComboBoxArithmetic;
    private javax.swing.JComboBox<String> jComboBoxAssign;
    private javax.swing.JComboBox<String> jComboBoxComment;
    private javax.swing.JComboBox<String> jComboBoxComparison;
    private javax.swing.JComboBox<String> jComboBoxConstant;
    private javax.swing.JComboBox<String> jComboBoxID;
    private javax.swing.JComboBox<String> jComboBoxKeyWords;
    private javax.swing.JComboBox<String> jComboBoxOthers;
    private javax.swing.JEditorPane jPanelGraphviz;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAnalyze;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelReportTable;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanelAnalyze;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelFile;
    private javax.swing.JPanel jPanelGraph;
    private javax.swing.JPanel jPanelHelp;
    //private javax.swing.JPanel jPanelPaint;
    private javax.swing.JPanel jPanelReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaAbout;
    private javax.swing.JTextArea jTextAreaAbout1;
    private javax.swing.JTextPane jTextPaneAnalyze;
    private javax.swing.JTextPane jTextPaneError;
    private javax.swing.JTextPane jTextPanePaint;
    // End of variables declaration
}